### ISSUE TITLE
Add more owners to the crate?

### ISSUE THREAD

**Issue by frewsxcv** [georust/geocoding#21]
Hey @groteworld, are you open to adding more owners to the crate on crates.io? If so, I think you can do `cargo owner -a georust/core`. No worries if you want to be the sole owner!

Also sorry I just pushed a few commits straight to master 🙈 I'll use PRs going forward

**Comment by urschrei** [comment]
@frewsxcv I take it this hasn't happened? I wonder whether we can ping Blake using some sort of alternate medium…

**Comment by frewsxcv** [comment]
Nah haven't heard anything. Blake is still the sole owner

**Comment by groteworld** [comment]
Sorry sorry! Didn’t look at personal emails today! Soon as I get home I’ll
add a few people. Thanks for the reminder

**Comment by urschrei** [comment]
@groteworld Great, thanks!

**Comment by groteworld** [comment]
@georust/core has been added!
