### ISSUE TITLE
Add option or default language=native (Opencage)

### ISSUE THREAD

**Issue by terry90** [georust/geocoding#37]
It's not uncommon to use the location's native language when geocoding (especially for forward geocoding).
Could we consider adding this as a default ? or would it be better to make it an optional parameter ?

**Comment by freyfogle** [comment]
As someone who lives in Barcelona I can tell you there are cases where it is highly contentious what the "native" language is. 

In the case of OSM supplying "native" returns non-intuitive results. For example the "native" name for Belgium is a concatenation of all three languages of Belgium ie `België / Belgique / Belgien` Probably the only thing all three groups can agree on is that that is not correct ;-) 

At OpenCage we take the approach of
a. obey whatever the user explicitly defined (which can also be `language=native`)
b. obey the browser language
c. default to English

https://opencagedata.com/api#language

**Comment by terry90** [comment]
Sure, but for now it's not even possible to chose the language when geocoding with this crate. I understand the case of non-intuitive native languages though.
I'll write a PR for this if this is OK. something to provide optional parameters, with defaults
