### ISSUE TITLE
crates publishing team

### ISSUE THREAD

**Issue by michaelkirk** [georust/geocoding#40]
👋 Hi @groteworld - you're the sole user-owner of the [geocoding crate on crates.io](https://crates.io/crates/geocoding).

Following up on https://github.com/georust/meta/pull/21, I created a new [geocoding-publishers](https://github.com/orgs/georust/teams/geocoding-publishers) team for publishing to crates.io with you as it's sole member and maintainer. 

Could you please [update the crates.io owners](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner)? Specifically:

---

- [ ] update **geocoding crate** owners on crates.io:
```
cd geocoding

# 💥 remove large publishing group
cargo owner --remove github:georust:core
# 🔐 add small publishing group
cargo owner --add github:georust:geocoding-publishers

# 🚨 you're currently the only user-owner of geocoding.  Consider adding @urschrei or @frewsxcv as a user-owner, 
# that way if for some reason you become inaccessible we have someone else who can edit the owners. 
# See https://github.com/rust-lang/crates.io/issues/2906
cargo owner --add urschrei
cargo owner --add frewsxcv

# make sure everything looks good 👀 
cargo owner --list
```
---

And if there's anyone else you'd like to be able to publish the crates, feel free to add them to your publishing team, or as a user-owner. Consider that user-owners, as opposed to owners-via-team, can themselves edit the crate's owners, which could be desirable, or not, depending.

In particular @urschrei and @frewsxcv have been pretty active in this crate. Consider adding them to [geocoding-publishers](https://github.com/orgs/georust/teams/geocoding-publishers) if not as explicit user-owners, otherwise they will lose publishing access... though I suppose as GH organization owners, they could technically add themselves to the GH team once you've added it to the cargo owners.

Let me know if you have any questions, or you can review https://github.com/georust/meta/pull/21.

**Comment by groteworld** [comment]
done
