### ISSUE TITLE
migrate CI to github actions

### ISSUE THREAD

**Issue by michaelkirk** [georust/geocoding#49]
Build is stalled: https://github.com/georust/geocoding/pull/48#issuecomment-896745354

<img width="954" alt="Screen Shot 2021-08-11 at 9 35 59 AM" src="https://user-images.githubusercontent.com/217057/129068178-584e68bb-89fa-4b46-afb8-10ef67b33df5.png">

It seems like maybe bors is set up OK and has appropriate access, but the build status never updates.

I think this is because this repo still relies on travis-ci. 

There's too much verbage here for me to be willing to read right now: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

But I believe the take away is that travis-ci is no longer an option for us unless we want to pay, so I'd recommend switching to github actions instead of travis, like we have for most of our other repositories.

**Comment by urschrei** [comment]
Although I seem to recall that GHA doesn't allow network access, which would be a spanner in the works of our (arguably not particularly useful can-we-interact-with-the-API tests).

**Comment by urschrei** [comment]
https://github.com/urschrei/rust-geocoding/runs/3303511875?check_suite_focus=true

😬

**Comment by michaelkirk** [comment]
> https://github.com/hyperium/hyper/issues/1009

#48 updated hyper - maybe there is a corresponding change to make?

@elwerene - Were you able to have the tests passing locally?

**Comment by urschrei** [comment]
> maybe related? hyperium/hyper#1009

Ha I just updated reqwest and hyper

**Comment by urschrei** [comment]
OK well I've completely confused myself now. That'll teach me to think "this will be a five minute PR". Tomorrow it is!

**Comment by elwerene** [comment]
> maybe related? [hyperium/hyper#1009](https://github.com/hyperium/hyper/issues/1009)
> 
> #48 updated hyper - maybe there is a corresponding change to make?
> 
> @elwerene - Were you able to have the tests passing locally?

no - but not on master either :/

**Comment by lnicola** [comment]
Drive-by remark: wouldn't it make sense to enable `default-tls` for `reqwest` if you need HTTPS?
